config-ver: '0'


configuration:
  test1: hi

  # A comment
  test2: "text"
  test3: true

  test4: 
    test5: 2

test6: another text

duplicated-keys:
  test7: true
  test:
    test7: "duplicated key"

